title: C# Discord Community
description: The community guide for the C# Discord community. Learn who, what and where and how.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
discord_invite: https://discord.gg/FTqNnyS